# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

  pool:
  vmImage: 'windows-latest'

steps:
- script: |
    powershell.exe -NoProfile -InputFormat None -ExecutionPolicy AllSigned -Command "[System.Net.ServicePointManager]::SecurityProtocol = 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://dl-cli.pstmn.io/install/win64.ps1'))"
  displayName: 'Install Postman CLI'

- task: CmdLine@2
  displayName: 'Run automated API tests using Postman CLI'
  inputs:
    script: |
        postman login --with-api-key $(POSTMAN_API_KEY)
        # Run your collection using Postman CLI
        postman collection run "54809398-3b071a38-677a-4a40-b038-7f6a6bc3ccb7"
